In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler


data = pd.read_csv('/content/sample_features.csv')

X = data[['core_frequency', 'max_amplitude', 'average_activation', 'duration']]
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=445)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

kernels = ['linear', 'poly', 'rbf']
models = {}

for kernel in kernels:
    model = SVC(kernel=kernel, degree=3 if kernel == 'poly' else 1)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    models[kernel] = {
        'model': model,
        'accuracy': accuracy_score(y_test, y_pred),
        'conf_matrix': confusion_matrix(y_test, y_pred),
        'classification_report': classification_report(y_test, y_pred)
    }

# Display the results
for kernel, data in models.items():
    print(f"\nKernel: {kernel}")
    print(f"Accuracy: {data['accuracy']:.2f}")
    print("Confusion Matrix:\n", data['conf_matrix'])
    print("Classification Report:\n", data['classification_report'])


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))



Kernel: linear
Accuracy: 0.53
Confusion Matrix:
 [[ 4  0  4 12  0  0 25  0]
 [ 0  1  4  0  0  1  4  0]
 [ 0  2 18  1  0  0  2  0]
 [ 0  1  2 72  0  0  8 14]
 [ 2  0  6 12  0  0 11  5]
 [ 0  0  4  0  0  0  4  0]
 [ 1  3  4 10  0  0 73 16]
 [ 0  0  0  8  0  0 13 31]]
Classification Report:
               precision    recall  f1-score   support

        clap       0.57      0.09      0.15        45
      cymbal       0.14      0.10      0.12        10
         hat       0.43      0.78      0.55        23
        kick       0.63      0.74      0.68        97
        perc       0.00      0.00      0.00        36
        ride       0.00      0.00      0.00         8
       snare       0.52      0.68      0.59       107
         tom       0.47      0.60      0.53        52

    accuracy                           0.53       378
   macro avg       0.35      0.37      0.33       378
weighted avg       0.47      0.53      0.47       378


Kernel: poly
Accuracy: 0.47
Confusion Matrix:
 [[ 3  1  2

/bin/bash: line 1: ageck314: No such file or directory
